name: purplestore
description: A database that store data on Nostr.
version: 1.0.0
repository: https://github.com/nogringo/purplestore

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0
  ndk: ^0.5.1
  path: ^1.9.1
  sembast: ^3.8.5+1
  uuid: ^4.5.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
